# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'http://gitlab.obplay.cn:18080/BlueSky/privatecocoapodsrepo.git'

target 'BSKNetwork' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Alamofire', '~> 4.8.2'
  pod 'BSKConsole', '= 0.1.0'
  # Pods for BSKNetwork

end
